# Generated by Django 5.0.6 on 2024-06-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "-deadline", "name"]},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "worker",
                "verbose_name_plural": "workers",
            },
        ),
    ]
